bcgov/BC-Wallet-Demo

DockerfileClient, DockerfileServer
added docker configurations for openshift
=> Feature docker

server/src/controllers/CredDefService.ts
added support for test and prod environments by making server fetch the agent did before pushing cred defs
=> added support for cred defs in test and prod

server/src/content/student/useCases/OnlineStore.ts
=> changed date predicate to be today's date

client/public/index.html, client/src/pages/landing/LandingPage.tsx
Updated the site metadata preview:
Metadata title: "BC Wallet Showcase"
Metadata description: "Explore how you can use BC Wallet to prove things about yourself, in a way that's safe and secure."
Resolves: #39
=> updated site preview text

client/package.json
fixed the bundle being loaded from the wrong location
=> updated home route

client/src/pages/onboarding/components/WalletModal.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx
Resolves: #61 
also added button that lets user skip credential issuance screen
=> made wallet app store links open in new tab

client/src/pages/dashboard/components/DemoCompletedModal.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx
=> added survey links to showcase end

client/src/pages/dashboard/components/DemoCompletedModal.tsx
=> temporarily disabled the survey functionality

client/src/pages/dashboard/components/DemoCompletedModal.tsx
=> updated survey link

client/src/pages/onboarding/steps/PickCharacter.tsx
added character selection back to demo
Resolves: #78
=> added character selection back

client/src/pages/onboarding/steps/PickCharacter.tsx
Allow app to switch between single character mode and full character mode by setting `REACT_APP_INSIGHTS_PROJECT_ID` to be empty or `FULL_DEMO`
=> Set full demo with env variable

client/src/pages/dashboard/components/ProfileCard.tsx, client/src/pages/onboarding/steps/PickCharacter.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx, client/src/pages/useCase/steps/StepProof.tsx, server/src/content/Characters.ts, server/src/content/UseCases.ts, server/src/content/student/Student.ts, server/src/content/student/useCases/OnlineStore.ts, server/src/content/verifiedPerson/VerifiedPerson.ts, server/src/content/verifiedPerson/VerifiedPersonUseCases.ts, server/src/content/verifiedPerson/useCases/DigitalId.ts, server/src/controllers/CredDefService.ts
Added support for Verified Person credential from multiple environments. Proof request restrictions have been relaxed to only match the schema name.
=> relaxed proof request rules and added PR for VP

server/src/content/verifiedPerson/VerifiedPerson.ts
=> fixed vp character id conflict

server/src/content/verifiedPerson/VerifiedPerson.ts
Fixed verified person skip wallet screen
=> fix vp skip wallet screen

client/public/index.html
Added snowplow analytics to site
=> added snowplow analytics

DockerfileClient, client/src/customComponents/joyce/onboardingUtils/OnboardingUtils.tsx, client/src/pages/useCase/steps/StepProof.tsx, client/src/slices/types.ts, client/src/utils/OnboardingUtils.tsx, server/src/content/businessWoman/useCases/CourtServices.ts, server/src/content/lawyer2/Lawyer2.ts, server/src/content/lawyer2/useCases/CourtServices.ts, server/src/content/student/Student.ts, server/src/content/student/useCases/OnlineStore.ts, server/src/content/student/useCases/StudyRoom.ts, server/src/content/types.ts, server/src/content/verifiedPerson/useCases/DigitalId.ts, server/src/controllers/CredDefService.ts
Fixed docker file permissions in build process
=> Fix web dockerfile

client/src/customComponents/joyce/onboardingUtils/OnboardingUtils.tsx, client/src/pages/useCase/steps/StepProof.tsx, client/src/slices/types.ts, client/src/utils/OnboardingUtils.tsx, server/src/content/businessWoman/useCases/CourtServices.ts, server/src/content/lawyer2/Lawyer2.ts, server/src/content/lawyer2/useCases/CourtServices.ts, server/src/content/student/Student.ts, server/src/content/student/useCases/OnlineStore.ts, server/src/content/student/useCases/StudyRoom.ts, server/src/content/types.ts, server/src/content/verifiedPerson/useCases/DigitalId.ts, server/src/controllers/CredDefService.ts
=> updated wording across demo

DockerfileClient, client/src/customComponents/joyce/onboardingUtils/OnboardingUtils.tsx, client/src/pages/useCase/steps/StepProof.tsx, client/src/slices/types.ts, client/src/utils/OnboardingUtils.tsx, server/src/content/businessWoman/useCases/CourtServices.ts, server/src/content/lawyer2/Lawyer2.ts, server/src/content/lawyer2/useCases/CourtServices.ts, server/src/content/student/Student.ts, server/src/content/student/useCases/OnlineStore.ts, server/src/content/student/useCases/StudyRoom.ts, server/src/content/types.ts, server/src/content/verifiedPerson/useCases/DigitalId.ts, server/src/controllers/CredDefService.ts
Reverts bcgov/BC-Wallet-Demo#134
=> Revert "Fix web dockerfile"

DockerfileClient
=> changed permissions to root npm folder

DockerfileClient
=> moved permission change to after npm install

client/src/pages/dashboard/components/ProfileCard.tsx, server/src/content/lawyer2/useCases/CourtServices.ts
Made changes to sync up the `Follow this path` stepper with the court services demo:
Resolves: #105
=> fix: fixed the stepper display for court services

client/src/pages/onboarding/OnboardingPage.tsx, client/src/pages/onboarding/steps/PickCharacter.tsx
Changed the wording when the user first opens the character selection screen
Resolves: https://github.com/bcgov/BC-Wallet-Demo/issues/137
=> fixed character selection screen to be like animo

client/src/api/ConnectionApi.ts, client/src/api/CredentialApi.ts, client/src/api/ProofApi.ts, client/src/components/QRCode.tsx, client/src/customComponents/joyce/onboarding/OnboardingContainer.tsx, client/src/pages/onboarding/OnboardingContainer.tsx, client/src/pages/onboarding/OnboardingPage.tsx, client/src/pages/onboarding/steps/PickCharacter.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx, client/src/pages/useCase/Section.tsx, client/src/pages/useCase/steps/StepConnection.tsx, client/src/slices/connection/connectionSelectors.ts, client/src/slices/connection/connectionSlice.ts, client/src/slices/connection/connectionThunks.ts, client/src/slices/proof/proofSlice.ts, config/student.ts, server/package.json, server/src/agentRoutes/ConnectionController.ts, server/src/agentRoutes/CredentialController.ts, server/src/agentRoutes/ProofController.ts, server/src/controllers/CredDefService.ts, server/src/controllers/DeepLinkController.ts, server/src/index.ts, yarn.lock
- Upgraded AFJ version to 2.x
- Removed aries framework rest
Resolves: #149
=> feat: Upgraded afj to 2.x

client/src/pages/onboarding/OnboardingPage.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx, client/src/slices/connection/connectionSelectors.ts, client/src/slices/connection/connectionSlice.ts, client/src/slices/connection/connectionThunks.ts, client/src/slices/proof/proofSlice.ts, server/src/agentRoutes/CredentialController.ts, server/src/agentRoutes/ProofController.ts, server/src/index.ts
fixed linting issues and added route of openshift healthcheck
=> linting and added healthcheck

client/src/api/CredentialApi.ts, client/src/api/ProofApi.ts, client/src/customComponents/joyce/onboarding/OnboardingContainer.tsx, client/src/pages/onboarding/OnboardingContainer.tsx, client/src/pages/onboarding/OnboardingPage.tsx, client/src/pages/onboarding/components/Credential.tsx, client/src/pages/onboarding/components/StarterCredentials.tsx, client/src/pages/onboarding/steps/AcceptCredential.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx, client/src/pages/useCase/Section.tsx, client/src/pages/useCase/steps/StepConnection.tsx, client/src/pages/useCase/steps/StepCredential.tsx, client/src/pages/useCase/steps/StepProof.tsx, client/src/pages/useCase/steps/StepProofOOB.tsx, client/src/slices/connection/connectionSelectors.ts, client/src/slices/connection/connectionSlice.ts, client/src/slices/credentials/credentialsSlice.ts, client/src/slices/proof/proofSlice.ts, client/src/slices/proof/proofThunks.ts, client/src/utils/ProofUtils.tsx, server/src/controllers/CredDefService.ts, server/src/index.ts, server/src/utils/tractionHelper.ts, yarn.lock
added support for acapy traction integration
=> Feat acapy

client/src/api/ConnectionApi.ts, client/src/api/RevocationApi.ts, client/src/pages/dashboard/DashboardPage.tsx, client/src/pages/dashboard/components/RevocationContainer.tsx, client/src/pages/dashboard/components/RevocationItem.tsx, client/src/pages/dashboard/components/StartButton.tsx, client/src/pages/dashboard/components/UseCaseContainer.tsx, client/src/slices/credentials/credentialsSlice.ts, client/src/slices/types.ts, server/src/index.ts
added support for revocation via traction agent
Resolves: #132
=> added support for revocation

client/src/pages/dashboard/components/RevocationContainer.tsx, client/src/slices/credentials/credentialsSlice.ts
- fixed revocation list duplicating loading and completed states between entries
- fixed duplicate credentials being added to revocation list
=> fixed bug in revocation list making dup entries

DockerfileClient
fixed file permissions for running in node:fermium container
=> fix permissions/ in docker file build

client/src/api/CredentialApi.ts, client/src/api/ProofApi.ts, client/src/pages/onboarding/steps/AcceptCredential.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx, client/src/pages/useCase/steps/StepCredential.tsx, server/src/controllers/ConnectionController.ts, server/src/controllers/CredentialController.ts, server/src/controllers/DeepLinkController.ts, server/src/controllers/ProofController.ts, server/src/controllers/RevocationController.ts
- added deeplinks for tablets
- fixed deeplink functionality for all devices post traction upgrade  
Resolves: #140
=> feat: added deeplink support for tablets

client/src/pages/dashboard/DashboardPage.tsx, client/src/slices/preferences/preferencesSlice.ts, client/src/utils/KBar.tsx
Added revocation on/off menu item to the kbar secret menu:
=> added revocation on/off switch to kbar menu

client/src/components/QRCode.tsx, client/src/customComponents/joyce/onboarding/OnboardingContainer.tsx, client/src/pages/onboarding/OnboardingContainer.tsx, client/src/pages/onboarding/components/Credential.tsx, client/src/pages/onboarding/components/StarterCredentials.tsx, client/src/pages/onboarding/steps/AcceptCredential.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx, client/src/pages/useCase/Section.tsx, client/src/pages/useCase/steps/StepConnection.tsx, client/src/pages/useCase/steps/StepCredential.tsx, client/src/slices/credentials/credentialsSlice.ts, client/src/utils/Helpers.ts, server/src/controllers/DeepLinkController.ts
- Fixed issue where bottom nav buttons would sometimes not be enabled after accepting a credential through a deeplink
- Minor code cleanup with connection and credential state checks
=> fix: fixed issue with bottom nav buttons on deeplink

server/src/index.ts
added readiness check to allow uptime monitors to check if the traction agent is up and running
=> added check to test if agent is up

client/src/pages/useCase/steps/StepProof.tsx
Added listener to remove proof record immediately after it's been received
Resolves: #182
=> feat: remove proof record immediatly after we're done

client/src/api/CredentialApi.ts, client/src/pages/onboarding/components/StarterCredentials.tsx, client/src/pages/onboarding/steps/AcceptCredential.tsx, client/src/slices/credentials/credentialsSlice.ts, server/src/controllers/CredentialController.ts
previously the requests to monitor the credential status were going to the wrong API endpoint. I've fixed the requests now so they're going tot he right place
=> fix: fixed the onboarding offer credential stage

server/config/lawyerCustom.ts, server/config/studentCustom.ts, server/src/utils/dateint.ts
used a calculated date offset from today's date in credentials and proof requests
Resolves: #191
=> Used relative date in creds and proofs

server/config/lawyerCustom.ts, server/config/studentCustom.ts
Incremented the schema versions for the new traction agents
=> feat: bumped schema versions

client/Caddyfile, server/src/index.ts
Updated health checks for front and backend
=> feat: updated health checks

server/src/utils/tractionHelper.ts
added exception to connection removal functionality
=> feat: updated for new endorser alias

client/src/api/ProofApi.ts, client/src/pages/useCase/steps/StepProof.tsx, client/src/slices/types.ts, server/config/lawyerCustom.ts, server/src/content/types.ts
added functionality to specify revocation interval in the configs,
added the revocation interval only to the photo attribute proof in the lawyer use case.
=> feat: added revocation interval only for lawyer

client/src/api/CharacterApi.ts, client/src/pages/onboarding/OnboardingPage.tsx, client/src/slices/characters/charactersThunks.ts, client/src/slices/preferences/preferencesSlice.ts, client/src/slices/types.ts, client/src/utils/KBar.tsx, server/config/lawyerCustom.ts, server/src/content/types.ts, server/src/controllers/CharacterController.ts, server/src/controllers/UseCaseController.ts
added support for hidden usecases, courtlibrary is hidden by default.
to enable all usecases go to the kbar menu during character selection and select `Show/Hide hidden usecases`
=> feat: added ability to hide usecases

client/src/api/CharacterApi.ts, client/src/components/ActionCTA.tsx, client/src/pages/dashboard/DashboardPage.tsx, client/src/pages/onboarding/OnboardingPage.tsx, client/src/slices/characters/charactersThunks.ts, client/src/slices/types.ts, server/config/lawyerCustom.ts, server/src/content/types.ts, server/src/controllers/CharacterController.ts, server/src/controllers/DeepLinkController.ts, server/src/controllers/UseCaseController.ts
previously the toggle hidden usecases functionalliyt was broken in the BC showcase. I changed the functionality to use the UI to hide the usecase instead of doing it on the server side
=> Fix hidden usecase

client/src/pages/dashboard/components/UseCaseItem.tsx, server/config/lawyerCustom.ts
Added initial support for attestation use case
=> feat: initial support for attestation

client/src/api/ConnectionApi.ts, client/src/pages/onboarding/steps/SetupConnection.tsx, client/src/pages/useCase/steps/StepConnection.tsx, client/src/slices/connection/connectionThunks.ts, server/src/controllers/ConnectionController.ts
Added support for goal codes during credential issuance and proof request
=> feat: Added support for goalcodes

client/Caddyfile, client/package.json, client/src/api/BaseUrl.ts, client/src/pages/onboarding/steps/AcceptCredential.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx, client/src/pages/useCase/steps/StepConnection.tsx, client/src/pages/useCase/steps/StepProof.tsx, server/package.json, server/src/controllers/WebhookController.ts, server/src/index.ts, server/src/utils/tractionHelper.ts, yarn.lock
Fixed issue with firefox websockets
=> Feat-socket.io-websocks

client/Caddyfile, client/src/api/BaseUrl.ts, client/src/pages/onboarding/steps/AcceptCredential.tsx, client/src/pages/onboarding/steps/SetupConnection.tsx, client/src/pages/useCase/steps/StepConnection.tsx, client/src/pages/useCase/steps/StepProof.tsx, server/src/index.ts
=> fixed socket config

.github/actions/build_docker/action.yml, .github/actions/trivy-scan/action.yaml, .github/workflows/on_pr_closed.yaml, .github/workflows/on_pr_opened.yaml, .github/workflows/on_push_main.yaml, infra-docs/README.md
This PR restructures CI/CD workflows into organized GitHub Actions files and introduces supporting documentation.
- Refactored and modularized GitHub Actions for CI/CD processes.
- Workflows now include: PR open/close event handling, main branch deployments, Trivy security scans, Docker image builds, and ephemeral PR environment provisioning.
- Overview of the event-driven CI/CD pipeline.
- Step-by-step breakdown of testing, building, scanning, and deployment stages.
- Manual promotion process for staging and production environments.
- Image tagging strategy and updated directory structure.
=> Refactor GitHub Actions workflow for OpenShift deployment

.github/workflows/on_push_main.yaml
Preemptively adding a workflow to build and deploy the showcase builder. This will facilitate the ability to test and deploy from the `showcase-builder` branch.
=> Add workflow to build and deploy showcase builder
